name: bloc_hydrated
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter

  meta: 1.15.0

  bloc: 8.1.4
  hydrated_bloc: 9.1.5
  path_provider: 2.1.5
  flutter_bloc: 8.1.4
  freezed_annotation: 2.4.4

dev_dependencies:
  build_runner: 2.4.13
  freezed: 2.5.7

flutter:
  uses-material-design: true
