name: fb_auth_bloc
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter

  meta: 1.15.0

  # firebase
  firebase_core: 3.8.1
  firebase_auth: 5.3.4
  cloud_firestore: 5.5.1

  # state
  bloc: 8.1.4
  flutter_bloc: 8.1.4

  # util
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  flutter_dotenv: 5.2.1
  recase: 4.1.0
  email_validator: 3.0.0
  gap: 3.0.1

  # network
  http: 1.2.2

dev_dependencies:
  build_runner: 2.4.13
  freezed: 2.5.7
  json_serializable: 6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
